[package]
name = "pgxr_example_query"
version = "0.1.0"
authors = ["clia <clia@163.com>"]

[lib]
name = "pgxr_example_query"
crate-type = ["cdylib"]

[dependencies]

[dependencies.pgxr]
path = "../../"
